---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /Homelab/Files/AppData/Config/Sonarr:/config
      - /home/ganesh/docker/jellyfin/data/tvshows:/tv #optional
      - /home/ganesh/docker/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped