---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_VOLUME:-/Homelab/Files/AppData/Config/Sonarr}:/config
      - ${MEDIA_FOLDER:-/home/ganesh/docker/jellyfin/data/tvshows}:/tv #optional
      - ${DOWNLOAD_LOCATION:-/home/ganesh/docker/downloads}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped