---
version: "2.1"
services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - PASSWORD=${PWD:-password} 
      - HASHED_PASSWORD= 
      - SUDO_PASSWORD=${SUDO_PWD:-password} 
      - SUDO_PASSWORD_HASH= 
      - PROXY_DOMAIN=code-server.my.domain 
    volumes:
      - ${CONFIG_VOLUME:-/Homelab/Files/AppData/Config/code-server}:/config
      - ${WORKSPACE_VOLUME-/home/ganesh/docker/code}:/config/workspace
    ports:
      - ${PORT:-6443}:8443
    restart: unless-stopped
