---
version: "3.0"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_VOLUME:-/Homelab/Files/AppData/Config/Qbitorrent}:/config
      - ${DOWNLOAD_LOCATION:-/home/ganesh/docker/downloads}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped