---
version: "2.1"
services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=${TZ:-Asia/Kolkata}
      - SUBDOMAINS=${SUBDOMAIN}
      - TOKEN={TOKEN} # token from duckdns
      - LOG_FILE=false #optional
    volumes:
      - /Homelab/Files/AppData/Config/duckdns:/config #optional
    restart: unless-stopped
