---
version: "3.0"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /Homelab/Files/AppData/Config/Nextcloud:/config
      - /home/ganesh/docker/data:/data
    ports:
      - 4443:443
    restart: unless-stopped