---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_VOLUME:-/Homelab/Files/AppData/Config/Radarr}:/config
      - ${MEDIA_FOLDER:-/home/ganesh/docker/jellyfin/data/movies/Movies}:/movies #optional
      - ${DOWNLOAD_LOCATION:-/home/ganesh/docker/downloads}:/downloads #optional
    ports:
      - ${PORT:-7878}:7878
    restart: unless-stopped