---
version: "2.1"
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
    volumes:
      - /Homelab/Files/AppData/Config/Jackett:/config
      - /home/ganesh/docker/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
