version: "3.0"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Kolkata
    volumes:
      - /Homelab/Files/AppData/Config/jellyfin:/config
      - /home/ganesh/docker/jellyfin/data/tvshows:/data/tvshows
      - /home/ganesh/docker/jellyfin/data/movies:/data/movies
      - /home/ganesh/docker/jellyfin/data/movies:/data/music
      - /dev/shm:/config/data/transcoding-temp/transcodes
      - /opt/vc/lib:/opt/vc/lib   
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/vchiq:/dev/vchiq 
    restart: unless-stopped
