version: "3.0"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Asia/Kolkata}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${CONFIG_DIR:-/Homelab/Files/AppData/Config/jellyfin}:/config
      - ${MEDIA_FOLDER:-/home/ganesh/docker/jellyfin/data/}:/data/Media
      - /dev/shm:/config/data/transcoding-temp/transcodes
      - /opt/vc/lib:/opt/vc/lib   
      - /etc/ld.so.conf.d/00-vmcs.conf:/etc/ld.so.conf.d/00-vmcs.conf ## Path needed for libraries
    ports:
      - 8096:${PORT:-8096}
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri 
    restart: unless-stopped