version: "3.0"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Kolkata
    volumes:
      - /Homelab/Files/AppData/Config/jellyfin:/config
      - /home/ganesh/docker/jellyfin/data/tvshows:/data/tvshows
      - /home/ganesh/docker/jellyfin/data/movies:/data/movies
      - /home/ganesh/docker/jellyfin/data/movies:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
