---
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ${CONFIG_VOLUME:-/Homelab/Files/AppData/Config/Nextcloud}:/config
      - ${NEXTCLOUD_DATA_DIR:-/home/ganesh/docker/data}:/data
    ports:
      - ${PORT:-4443}:443
    restart: unless-stopped
